#lang scheme

(require (planet schematics/schemeunit:3:4)
         (planet schematics/schemeunit:3/text-ui))

(require "Sicp/SicpTest/Ch1/Sec1/Part1.scm"
         "Sicp/SicpTest/Ch1/Sec1/Part2.scm"
         "Sicp/SicpTest/Ch1/Sec1/Part3.scm"
         "Sicp/SicpTest/Ch1/Sec1/Part4.scm"
         "Sicp/SicpTest/Ch1/Sec1/Part5.scm"
         "Sicp/SicpTest/Ch1/Sec1/Part6.scm"
         "Sicp/SicpTest/Ch1/Sec1/Part7.scm"
         "Sicp/SicpTest/Ch1/Sec1/Part8.scm"
         "Sicp/SicpTest/Ch1/Sec2/Part1.scm"
         "Sicp/SicpTest/Ch1/Sec2/Part2.scm"
         "Sicp/SicpTest/Ch1/Sec2/Part3.scm"
         "Sicp/SicpTest/Ch1/Sec2/Part4.scm"
         "Sicp/SicpTest/Ch1/Sec2/Part5.scm"
         "Sicp/SicpTest/Ch1/Sec2/Part6.scm"
         "Sicp/SicpTest/Ch1/Sec3/Part1.scm"
         "Sicp/SicpTest/Ch1/Sec3/Part2.scm"
         "Sicp/SicpTest/Ch1/Sec3/Part3.scm"
         "Sicp/SicpTest/Ch1/Sec3/Part4.scm"
         "Sicp/SicpTest/Ch2/Sec1/Part1.scm"
         "Sicp/SicpTest/Ch2/Sec1/Part2.scm"
         "Sicp/SicpTest/Ch2/Sec1/Part3.scm"
         "Sicp/SicpTest/Ch2/Sec1/Part4.scm"
         "Sicp/SicpTest/Ch2/Sec2/Part1.scm"
         "Sicp/SicpTest/Ch2/Sec2/Part2.scm"
         "Sicp/SicpTest/Ch2/Sec2/Part3.scm"
         "Sicp/SicpTest/Ch2/Sec2/Part4.scm"
         "Sicp/SicpTest/Ch2/Sec3/Part1.scm"
         "Sicp/SicpTest/Ch2/Sec3/Part2.scm"
         "Sicp/SicpTest/Ch2/Sec3/Part3.scm"
         "Sicp/SicpTest/Ch2/Sec3/Part4.scm"
         "Sicp/SicpTest/Ch2/Sec4/Part1.scm"
         "Sicp/SicpTest/Ch2/Sec4/Part2.scm"
         "Sicp/SicpTest/Ch2/Sec4/Part3.scm"
         "Sicp/SicpTest/Ch2/Sec5/Part1.scm"
         "Sicp/SicpTest/Ch2/Sec5/Part2.scm"
         "Sicp/SicpTest/Ch2/Sec5/Part3.scm"
         "Sicp/SicpTest/Ch3/Sec1/Part1.scm"
         "Sicp/SicpTest/Ch3/Sec1/Part2.scm"
         "Sicp/SicpTest/Ch3/Sec1/Part3.scm"
         "Sicp/SicpTest/Ch3/Sec2/Part1.scm"
         "Sicp/SicpTest/Ch3/Sec2/Part2.scm"
         "Sicp/SicpTest/Ch3/Sec2/Part3.scm"
         "Sicp/SicpTest/Ch3/Sec2/Part4.scm"
         "Sicp/SicpTest/Ch3/Sec3/Part1.scm"
         "Sicp/SicpTest/Ch3/Sec3/Part2.scm"
         "Sicp/SicpTest/Ch3/Sec3/Part3.scm"
         "Sicp/SicpTest/Ch3/Sec3/Part4.scm"
         "Sicp/SicpTest/Ch3/Sec3/Part5.scm"
         "Sicp/SicpTest/Ch3/Sec4/Part1.scm"
         "Sicp/SicpTest/Ch3/Sec4/Part2.scm"
         "Sicp/SicpTest/Ch3/Sec5/Part1.scm"
         "Sicp/SicpTest/Ch3/Sec5/Part2.scm"
         "Sicp/SicpTest/Ch3/Sec5/Part3.scm"
         "Sicp/SicpTest/Ch3/Sec5/Part4.scm"
         "Sicp/SicpTest/Ch3/Sec5/Part5.scm"
         "Sicp/SicpTest/Ch4/Sec1/Part1.scm"
         "Sicp/SicpTest/Ch4/Sec1/Part2.scm"
         "Sicp/SicpTest/Ch4/Sec1/Part3.scm"
         "Sicp/SicpTest/Ch4/Sec1/Part4.scm"
         "Sicp/SicpTest/Ch4/Sec1/Part5.scm"
         "Sicp/SicpTest/Ch4/Sec1/Part6.scm"
         "Sicp/SicpTest/Ch4/Sec1/Part7.scm"
         "Sicp/SicpTest/Ch4/Sec2/Part1.scm"
         "Sicp/SicpTest/Ch4/Sec2/Part2.scm"
         "Sicp/SicpTest/Ch4/Sec2/Part3.scm"
         "Sicp/SicpTest/Ch4/Sec3/Part1.scm"
         "Sicp/SicpTest/Ch4/Sec3/Part2.scm"
         "Sicp/SicpTest/Ch4/Sec3/Part3.scm"
         "Sicp/SicpTest/Ch4/Sec4/Part1.scm"
         "Sicp/SicpTest/Ch4/Sec4/Part2.scm"
         "Sicp/SicpTest/Ch4/Sec4/Part3.scm"
         "Sicp/SicpTest/Ch4/Sec4/Part4.scm"
         "Sicp/SicpTest/Ch5/Sec1/Part1.scm"
         "Sicp/SicpTest/Ch5/Sec1/Part2.scm"
         "Sicp/SicpTest/Ch5/Sec1/Part3.scm"
         "Sicp/SicpTest/Ch5/Sec1/Part4.scm"
         "Sicp/SicpTest/Ch5/Sec1/Part5.scm"
         "Sicp/SicpTest/Ch5/Sec2/Part1.scm"
         "Sicp/SicpTest/Ch5/Sec2/Part2.scm"
         "Sicp/SicpTest/Ch5/Sec2/Part3.scm"
         "Sicp/SicpTest/Ch5/Sec2/Part4.scm"
         "Sicp/SicpTest/Ch5/Sec3/Part1.scm"
         "Sicp/SicpTest/Ch5/Sec3/Part2.scm"
         "Sicp/SicpTest/Ch5/Sec4/Part1.scm"
         "Sicp/SicpTest/Ch5/Sec4/Part2.scm"
         "Sicp/SicpTest/Ch5/Sec4/Part3.scm"
         "Sicp/SicpTest/Ch5/Sec4/Part4.scm"
         "Sicp/SicpTest/Ch5/Sec5/Part1.scm"
         "Sicp/SicpTest/Ch5/Sec5/Part2.scm"
         "Sicp/SicpTest/Ch5/Sec5/Part3.scm"
         "Sicp/SicpTest/Ch5/Sec5/Part4.scm"
         "Sicp/SicpTest/Ch5/Sec5/Part5.scm"
         "Sicp/SicpTest/Ch5/Sec5/Part6.scm"
         "Sicp/SicpTest/Ch5/Sec5/Part7.scm"
)

(define all-tests
  (test-suite
    "tests for SICP"
    (sicp-test-sicptest-ch1-sec1-part1)
    (sicp-test-sicptest-ch1-sec1-part2)
    (sicp-test-sicptest-ch1-sec1-part3)
    (sicp-test-sicptest-ch1-sec1-part4)
    (sicp-test-sicptest-ch1-sec1-part5)
    (sicp-test-sicptest-ch1-sec1-part6)
    (sicp-test-sicptest-ch1-sec1-part7)
    (sicp-test-sicptest-ch1-sec1-part8)
    (sicp-test-sicptest-ch1-sec2-part1)
    (sicp-test-sicptest-ch1-sec2-part2)
    (sicp-test-sicptest-ch1-sec2-part3)
    (sicp-test-sicptest-ch1-sec2-part4)
    (sicp-test-sicptest-ch1-sec2-part5)
    (sicp-test-sicptest-ch1-sec2-part6)
    (sicp-test-sicptest-ch1-sec3-part1)
    (sicp-test-sicptest-ch1-sec3-part2)
    (sicp-test-sicptest-ch1-sec3-part3)
    (sicp-test-sicptest-ch1-sec3-part4)
    (sicp-test-sicptest-ch2-sec1-part1)
    (sicp-test-sicptest-ch2-sec1-part2)
    (sicp-test-sicptest-ch2-sec1-part3)
    (sicp-test-sicptest-ch2-sec1-part4)
    (sicp-test-sicptest-ch2-sec2-part1)
    (sicp-test-sicptest-ch2-sec2-part2)
    (sicp-test-sicptest-ch2-sec2-part3)
    (sicp-test-sicptest-ch2-sec2-part4)
    (sicp-test-sicptest-ch2-sec3-part1)
    (sicp-test-sicptest-ch2-sec3-part2)
    (sicp-test-sicptest-ch2-sec3-part3)
    (sicp-test-sicptest-ch2-sec3-part4)
    (sicp-test-sicptest-ch2-sec4-part1)
    (sicp-test-sicptest-ch2-sec4-part2)
    (sicp-test-sicptest-ch2-sec4-part3)
    (sicp-test-sicptest-ch2-sec5-part1)
    (sicp-test-sicptest-ch2-sec5-part2)
    (sicp-test-sicptest-ch2-sec5-part3)
    (sicp-test-sicptest-ch3-sec1-part1)
    (sicp-test-sicptest-ch3-sec1-part2)
    (sicp-test-sicptest-ch3-sec1-part3)
    (sicp-test-sicptest-ch3-sec2-part1)
    (sicp-test-sicptest-ch3-sec2-part2)
    (sicp-test-sicptest-ch3-sec2-part3)
    (sicp-test-sicptest-ch3-sec2-part4)
    (sicp-test-sicptest-ch3-sec3-part1)
    (sicp-test-sicptest-ch3-sec3-part2)
    (sicp-test-sicptest-ch3-sec3-part3)
    (sicp-test-sicptest-ch3-sec3-part4)
    (sicp-test-sicptest-ch3-sec3-part5)
    (sicp-test-sicptest-ch3-sec4-part1)
    (sicp-test-sicptest-ch3-sec4-part2)
    (sicp-test-sicptest-ch3-sec5-part1)
    (sicp-test-sicptest-ch3-sec5-part2)
    (sicp-test-sicptest-ch3-sec5-part3)
    (sicp-test-sicptest-ch3-sec5-part4)
    (sicp-test-sicptest-ch3-sec5-part5)
    (sicp-test-sicptest-ch4-sec1-part1)
    (sicp-test-sicptest-ch4-sec1-part2)
    (sicp-test-sicptest-ch4-sec1-part3)
    (sicp-test-sicptest-ch4-sec1-part4)
    (sicp-test-sicptest-ch4-sec1-part5)
    (sicp-test-sicptest-ch4-sec1-part6)
    (sicp-test-sicptest-ch4-sec1-part7)
    (sicp-test-sicptest-ch4-sec2-part1)
    (sicp-test-sicptest-ch4-sec2-part2)
    (sicp-test-sicptest-ch4-sec2-part3)
    (sicp-test-sicptest-ch4-sec3-part1)
    (sicp-test-sicptest-ch4-sec3-part2)
    (sicp-test-sicptest-ch4-sec3-part3)
    (sicp-test-sicptest-ch4-sec4-part1)
    (sicp-test-sicptest-ch4-sec4-part2)
    (sicp-test-sicptest-ch4-sec4-part3)
    (sicp-test-sicptest-ch4-sec4-part4)
    (sicp-test-sicptest-ch5-sec1-part1)
    (sicp-test-sicptest-ch5-sec1-part2)
    (sicp-test-sicptest-ch5-sec1-part3)
    (sicp-test-sicptest-ch5-sec1-part4)
    (sicp-test-sicptest-ch5-sec1-part5)
    (sicp-test-sicptest-ch5-sec2-part1)
    (sicp-test-sicptest-ch5-sec2-part2)
    (sicp-test-sicptest-ch5-sec2-part3)
    (sicp-test-sicptest-ch5-sec2-part4)
    (sicp-test-sicptest-ch5-sec3-part1)
    (sicp-test-sicptest-ch5-sec3-part2)
))

(run-tests all-tests)
